/**
 * Generates the repo-root llms.txt from the actual skill tree, so the index
 * can never drift from the skills that really ship (a stale hand-written
 * llms.txt advertises skills that no longer exist).
 *
 *   node .github/scripts/generate-llms-txt.ts          # write llms.txt
 *   node .github/scripts/generate-llms-txt.ts --check  # CI: fail if stale
 *
 * Requires Node >= 22.18 (run as .ts via native type-stripping, like the QA
 * scripts in cargo-gtm/scripts/).
 */

import { readdirSync, readFileSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const outPath = join(repoRoot, "llms.txt");
const repoUrl = "https://github.com/getcargohq/cargo-skills";

interface Skill {
  name: string;
  description: string;
  dir: string;
}

function parseFrontmatter(skillMdPath: string): Skill {
  const lines = readFileSync(skillMdPath, "utf8").split("\n");
  if (lines[0]?.trim() !== "---") {
    throw new Error(`${skillMdPath}: no frontmatter block`);
  }
  let name = "";
  let description = "";
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i];
    if (line.trim() === "---") break;
    const match = /^(name|description):\s*(.+)$/.exec(line);
    if (!match) continue;
    let value = match[2].trim();
    if (value.startsWith('"') && value.endsWith('"')) value = value.slice(1, -1);
    if (match[1] === "name") name = value;
    else description = value;
  }
  if (!name || !description) {
    throw new Error(`${skillMdPath}: missing name or description in frontmatter`);
  }
  return { name, description, dir: dirname(skillMdPath) };
}

function collectSkills(): Skill[] {
  const skills: Skill[] = [];
  for (const entry of readdirSync(repoRoot)) {
    const skillMd = join(repoRoot, entry, "SKILL.md");
    if (statSync(join(repoRoot, entry), { throwIfNoEntry: false })?.isDirectory() && existsSync(skillMd)) {
      skills.push(parseFrontmatter(skillMd));
    }
  }
  // Router first, then onboarding, then the outcome skill, then the rest A→Z —
  // same priority order the router itself teaches.
  const pinned = ["cargo", "cargo-quickstart", "cargo-gtm"];
  skills.sort((a, b) => {
    const pa = pinned.indexOf(a.name);
    const pb = pinned.indexOf(b.name);
    if (pa !== -1 || pb !== -1) {
      return (pa === -1 ? pinned.length : pa) - (pb === -1 ? pinned.length : pb);
    }
    return a.name.localeCompare(b.name);
  });
  return skills;
}

function render(skills: Skill[]): string {
  const skillLines = skills
    .map((s) => `- [${s.name}](${repoUrl}/blob/main/${s.name}/SKILL.md): ${s.description}`)
    .join("\n");

  return `# Cargo Agent Skills

> ${skills.length} agent skills that teach AI coding agents the Cargo CLI — sourcing, enrichment, verification, signal monitoring, workflow orchestration, workspace-as-code (CDK), diagnostics, and billing for GTM automation on [Cargo](https://getcargo.ai).

## Install

Paste into Claude Code, Codex, or Cursor:

\`\`\`
Install Cargo by following every step in https://api.getcargo.io/agent-install.txt
\`\`\`

Or manually:

\`\`\`bash
npx skills add getcargohq/cargo-skills
npm install -g @cargo-ai/cli
cargo-ai login --oauth
\`\`\`

## Skills

${skillLines}

## Documentation

- [Cargo](https://getcargo.ai)
- [Cargo API docs](https://docs.getcargo.ai/api-reference/introduction)
- [GitHub repository](${repoUrl})
- [CDK cookbooks — scaffoldable outcome templates](https://github.com/getcargohq/cargo-cookbooks)

<!-- Generated by .github/scripts/generate-llms-txt.ts — do not edit by hand. -->
`;
}

const generated = render(collectSkills());

if (process.argv.includes("--check")) {
  const current = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
  if (current !== generated) {
    console.error(
      "llms.txt is stale. Regenerate with: node .github/scripts/generate-llms-txt.ts",
    );
    process.exit(1);
  }
  console.log("llms.txt is up to date.");
} else {
  writeFileSync(outPath, generated);
  console.log(`Wrote ${outPath}`);
}
